src/styles/global/_default.scss
src/styles/global/core/_color.scss
src/styles/global/core/_palette.scss

Follow the convention of `color-set`, for new `palette-set` mixin which acts as a repository for mapping colors to a "theme".

Palette mixin for setting "theme" properties

---

package.json
src/styles/global/core/_color.scss

Fixes a variable name used to warn at compile time. Currently, the build halts with an 'undefined variable' error.
Note that the typical dev workflow (`npm start`) in `Network-Canvas` overwrites warnings with the server start message, making `@warn` less obvious (but I've left as `@warn` regardless).

Fix variable name in warning

---

lib/styles/components/inputs.scss
package.json
src/styles/components/inputs.scss

This better positions the error message for a radio group so it can be seen, and gives a slightly higher margin to the toggle button so it isn't cut off in forms. Fixes codaco/Network-Canvas#378.  Also fixes codaco/Network-Canvas#374.
To check, load the "teaching" protocol in the main app, and click the "new node" button on a name generator stage. Try to submit without filling it in, and the radio group should display an error now.

input tweaks

---

README.md
lib/styles/components/button.scss
lib/styles/components/icons.scss
lib/styles/components/inputs.scss
src/styles/components/button.scss
src/styles/components/icons.scss
src/styles/components/inputs.scss

Reduces generated CSS by 50%.
This means that compiling individual components like button is no longer
supported (at least until the structure here is reworked).
Tested with Server & NC.
Known issue: file naming. At this point, everything except 'all' should really be a partial, but I think that's academic in terms of generated output. I can follow up with another PR for that, but would like to get the core issue solved and avoid conflicts with the other outstanding branches.
Fixes #41.

Do not re-include files that output CSS

---

lib/styles/global/_default.scss
src/styles/global/_default.scss

Fixes #42.
I'm not entirely sure what the purpose of `$export-ui-classes` is, but I think this is the intended behavior: normalize comes before any other applied styles. I left the other 'export classes' in the same place.

Include normalize before other rules are applied

---

.sass-lint.yml
package.json

This adds the [bem naming helpers](https://github.com/codaco/Network-Canvas-UI/blob/master/styles/global/core/_bem.scss) to the whitelist (which includes `breakpoint` by default) for appearing after declarations in source.
I find the element & modifier mixins more readable than `__`/`--`, and they often must come after the base definition.
[Example use](https://github.com/codaco/Server/blob/master/src/renderer/styles/components/_tab_bar.scss#L4).
This is the only rule customization Server has after updating to 2.0.0.

Add BEM mixins to ordering whitelist

---

components/Fields/Checkbox.js
components/Fields/Radio.js

`input.checked` is only provided by redux form if `type="checkbox"` or `type="radio"` is provided to `<Field />`, so for the case that it isn't we can rely on the more reliable `input.value`, which is what redux-form aliases under the hood.
Resolves https://github.com/codaco/Architect/issues/132

Use input.value rather than expecting input.checked

---

styles/components/form/fields/_checkbox-group.scss
styles/components/form/fields/_radio-group.scss
styles/components/form/fields/_text.scss
styles/components/form/fields/_textarea.scss
styles/components/form/fields/_toggle-button-group.scss
styles/components/form/fields/_toggle-button.scss
styles/components/form/fields/_toggle.scss
styles/global/_default.scss

Fix most warnings from sass-lint. There's still an [`!important` declaration](https://github.com/codaco/Network-Canvas-UI/blob/1b9d988/styles/components/form/fields/_text.scss#L49); I don't know if that should be silenced or fixed.
[Edit: I removed the peerDependencies change for now as it breaks CI.]

Fix sass-lint warnings and clarify dependencies

---

components/Icon.js

Resolves #52.
This adds a warning when Icon (or, by extension, Button) is called with an incorrect name. We could instead use PropTypes.oneOf, but that feels a bit heavy.

Warn when Icon called with invalid name

---

components/Fields/Toggle.js

If fieldLabel isn't provided, render nothing.
Fixes #86.

Do not render label again

---

components/Transitions/Drop.js
styles/components/_dialog.scss
styles/components/_modal.scss
styles/global/_default.scss
utils/__mocks__/CSSVariables.js

This PR tweaks modal overlay styles
- Adjusts background color
- Adjusts the transition for the `Drop` preset

tweak modal overlay background color

---

components/Node.js
styles/components/_node.scss

This PR fixes node rendering glitchyness/corruption by removing the CSS filter drop shadow, and applying the effect with an SVG filter.
It also fixes a clipping issue with the selected and linking states.

fix node rendering corruption on iOS

---

components/Transitions/Drop.js
components/Transitions/Fade.js
utils/CSSVariables.js

This PR adds a hard error when accessing CSS variables before window loaded state, since doing this will cause the CSS variable value to be empty. This error can be avoided by removing calls to `getCSSVariableAs*` outside of the top level scope of a component definition, or by wrapping them within a function.

adds hard error when accessing CSS variables before all resources are loaded

---

components/Progress.js
components/__tests__/Progress.test.js
components/index.js
styles/components/_all.scss
styles/components/_progress.scss

Resolves #66.
Styling based on [the export comp](https://user-images.githubusercontent.com/1387940/49512785-e371eb00-f886-11e8-9749-d6059a7893c9.png) from https://github.com/codaco/Server/issues/200. Config vars are exposed at `:root` scope following the convention of other components.
Determinate (50%):
Indeterminate (animates gradient sideways):

Add a progress component

---

styles/global/_default.scss

This adds several more colors to the 'graph-data' palette definitions to better support larger numbers of series/types.
The colors are assumed to represent non-sequential types (e.g., for categorical value display). I picked colors in an order that seemed to maintain good separation, but there's nothing scientific about these choices.
Example use in pie chart:

Add additional graph color definitions

---

components/Transitions/Fade.js

For use in NC refinements to narrative, this adds an optional prop for `onExited`.

allow onExited override for Fade

---

components/Fields/ToggleButtonGroup.js

For codaco/Network-Canvas#878. This parallels what is done in CheckboxGroup and RadioGroup to avoid changing numbers to strings, by using the option index as the input value. 
Resolves codaco/Network-Canvas#878

use index so option values keep existing types

---

components/Transitions/Appear.js
components/Transitions/Drawer.js

Fixes some small console errors by refactoring Appear and Drawer to correctly use the JS CSS variable fetch utilities inside of their function definition.

refactor Appear and Drawer to correctly use getCSSVariable inside function

---

components/Transitions/Drawer.js

Fixes disappearing for initial rendering. This is an issue seen on Server, the export screen, when swapping which export type displays initially. With CSV as the default, selecting Graphml doesn't animate the height on disappear the first time.

fix height on initial rendering

---

package.json
src/components/Fields/Text.js
src/components/Fields/TextArea.js

This PR changes text inputs to use placeholder over label, rather than label over placeholder.
It also adds "search" as a valid text input type, which fixes #120.

prefer placeholder over label for text input, and allow search type

---

package-lock.json
package.json
src/components/Button.js
src/components/Node.js
src/styles/components/_button.scss
src/styles/components/_node.scss

This PR:
- Adjusts the node label size, to make sizes generally larger but also more consistent. 
- Adds javascript based ellipses for really long labels.
- Updates the button component to default to showing the icon on the left, as per the style guide.

Node Label and Button improvements

---

package-lock.json
package.json
src/components/Fields/LikertScale.js
src/components/Fields/Slider/Slider.js
src/components/Fields/VisualAnalogScale.js
stories/VisualAnalogScale.stories.js

Update LikertSlider and VisualAnalogScale to provide their own PropTypes where they differ from each other.
Required by: https://github.com/complexdatacollective/Interviewer/pull/1112

Fix slider prop warnings

---

package-lock.json
package.json
src/styles/components/_inputs.scss
src/styles/global/core/_normalize.scss

We have been plagued by an issue where users could not enter more than a single character of text on iOS devices. We initially believed this was due to Babel dependency breakages, but I have now isolated the fundamental cause, which was that we applied `user-select: none` to all elements, including `<input />` and `<textarea />`.
This was not immediately apparent as the cause, because the property requires prefixing on iOS, and older dependency versions erroneously failed to do this.
This release fixes the issue in a somewhat kludgy way by exempting these elements using chained `:not` statements.

Fix iOS text entry issues

---

src/components/Boolean/Boolean.js
src/components/Boolean/BooleanOption.js
src/components/Fields/Boolean.js
src/styles/components/form/_fields.scss
src/styles/components/form/fields/_boolean.scss
src/styles/components/form/fields/_checkbox.scss
src/styles/components/form/fields/_radio.scss
src/styles/components/form/fields/_toggle-button.scss
src/styles/components/form/fields/_toggle.scss
stories/Boolean.stories.js
stories/Boolean.stories.scss
stories/BooleanOption.stories.js

This PR changes some details of the new boolean input:
- Allows for option labels to be JSX so that specific content can be rendered when used on the dyad census
- Allows for <BooleanOption /> to have a custom class, as used on the tie strength census interface
- Adds a the clickable mixin for clickable affordances
- Adds the ability to have up to 5 options (and numerical option values), as used by the tie strength census.

implement clickable styles and other small features on boolean input

---

package.json
src/components/Button.js

Small patch that doesnt render the button content span if there is no content. Allows icon only buttons.

don't render button content if only icon is provided

---

package-lock.json
package.json
src/components/Fields/DatePicker/DatePicker.js
src/styles/components/form/fields/_date-picker.scss

Makes date picker an overlay. Clicking outside will close the overlay. Background color for the date-picker in interviewer was transparent, so this changes it to an opaque color so that elements underneath don't show through.

make date picker an overlay

---

.npmrc
package-lock.json
package.json
src/components/Boolean/BooleanOption.js
src/components/Fields/Checkbox.js
src/components/Fields/Markdown.js
src/components/Fields/MarkdownLabel.js
src/components/Fields/Text.js
src/components/Icon.js
stories/Text.stories.js

React markdown is expensive and was being rendered on keypress when
used with fields. This commit memoizes the markdown rendering components
so that they only re-render when the label changes.

Add React.memo to Markdown and MarkdownLabel
